source 'https://rubygems.org'

gem 'jekyll', '>= 4.2.0'
gem 'redcarpet'
gem 'rouge'
gem 'hash-joiner'
gem 'jekyll-last-modified-at', '>= 1.3.0'
gem 'jemoji', '>= 0.12.0'
gem 'jekyll-mentions', '>= 1.6.0'
gem 'jekyll-redirect-from', '>= 0.16.0'
gem 'jekyll-sitemap', '>= 1.4.0'
gem 'jekyll-autoprefixer'
gem 'jekyll-liquify'